# Establece la imagen base
FROM mysql:latest

# Establece las variables de entorno para la configuración de la base de datos
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Copia el archivo SQL de inicialización al contenedor
COPY init.sql /docker-entrypoint-initdb.d/

# Expone el puerto 3306 para acceder a la base de datos
EXPOSE 3306